# These are the current dependencies/versions for debugging purposes

name: turban
channels:
  - conda-forge
dependencies:
  - beartype
  - black
  - datashader # get rid of this eventually
  - gsw
  - hvplot # get rid of this eventually
  - jaxtyping
  - matplotlib
  - netCDF4
  - numba
  - numpy
  - pandas
  - panel # get rid of this eventually
  - pydantic
  - pytest
  - pytest-cov
  - scipy
  - setuptools
  - xarray