# These are the current dependencies for developing TURBAN

name: turban
channels:
  - conda-forge
dependencies:
  - beartype
  - black
  - gsw
  - jaxtyping
  - matplotlib
  - netCDF4
  - numba
  - numpy
  - pandas
  - pydantic
  - pytest
  - pytest-cov
  - pytest-markdown-docs
  - scipy
  - setuptools
  - xarray
    