# These are the current dependencies/versions for debugging purposes

name: turban
channels:
  - conda-forge
dependencies:
  - beartype
  - black
  - gsw
  - jaxtyping
  - matplotlib
  - netCDF4
  - numba
  - numpy
  - pandas
  - pydantic
  - pytest
  - pytest-cov
  - scipy
  - setuptools
  - xarray
  - pip:
    - markdown-pytest